// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	//tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	PhaserSidebar: [
		{
			"Getting Started": [
				"phaser/getting-started/what-is-phaser",
				"phaser/getting-started/installation",
				"phaser/getting-started/set-up-dev-environment",
				"phaser/getting-started/project-templates",
				"phaser/getting-started/making-your-first-phaser-game",
			],
		},

		{
			type: "category",
			label: "Concepts",
			items: [
				"phaser/concepts/actions",
				"phaser/concepts/animations",
				"phaser/concepts/audio",
				"phaser/concepts/cameras",
				"phaser/concepts/data-manager",
				"phaser/concepts/device",
				"phaser/concepts/display",
				"phaser/concepts/events",
				"phaser/concepts/fx",
				"phaser/concepts/game",

				{
					type: "category",
					label: "Game Objects",
					link: { type: "doc", id: "phaser/concepts/gameobjects" },
					items: [
						"phaser/concepts/gameobjects/components",
						"phaser/concepts/gameobjects/factories",
						"phaser/concepts/gameobjects/bitmap-text",
						"phaser/concepts/gameobjects/blitter",
						"phaser/concepts/gameobjects/container",
						"phaser/concepts/gameobjects/display-list",
						"phaser/concepts/gameobjects/dom-element",
						"phaser/concepts/gameobjects/graphics",
						"phaser/concepts/gameobjects/group",
						"phaser/concepts/gameobjects/image",
						"phaser/concepts/gameobjects/layer",
						"phaser/concepts/gameobjects/light",
						"phaser/concepts/gameobjects/mesh",
						"phaser/concepts/gameobjects/nine-slice",
						"phaser/concepts/gameobjects/particles",
						"phaser/concepts/gameobjects/plane",
						"phaser/concepts/gameobjects/render-texture",
						"phaser/concepts/gameobjects/rope",
						"phaser/concepts/gameobjects/shader",
						"phaser/concepts/gameobjects/sprite",
						"phaser/concepts/gameobjects/text",
						"phaser/concepts/gameobjects/tilesprite",
						"phaser/concepts/gameobjects/video",
					],
				},

				"phaser/concepts/geometry",
				"phaser/concepts/input",

				{
					type: "category",
					label: "Loader",
					link: { type: "doc", id: "phaser/concepts/loader" },
					items: [
						"phaser/concepts/loader/cache",
					],
				},

				"phaser/concepts/math",

				{
					type: "category",
					label: "Physics",
					link: { type: "doc", id: "phaser/concepts/physics" },
					items: [
						"phaser/concepts/physics/arcade",
						"phaser/concepts/physics/matter",
					],
				},

				"phaser/concepts/scale-manager",

				{
					type: "category",
					label: "Scenes",
					link: { type: "doc", id: "phaser/concepts/scenes" },
					items: [
						"phaser/concepts/scenes/cross-scene-communication",
					],
				},

				"phaser/concepts/textures",
				"phaser/concepts/time",
				"phaser/concepts/tweens",
				"phaser/concepts/utils",
			],
		},

		{
			type: "link",
			label: "API Documentation",
			href: "/api-documentation",
		},
		{
			type: "link",
			label: "Phaser Discord",
			href: "https://discord.gg/phaser",
		},
	],

	PhaserEditorSidebar: [
		{
			"Introduction": [
				"phaser-editor/intro/welcome",
				"phaser-editor/intro/distributions",
				"phaser-editor/intro/collaboration",
				"phaser-editor/intro/changelog"
			]
		},
		{
			"First Steps": [
				"phaser-editor/first-steps/download-and-install",
				"phaser-editor/first-steps/create-first-project",
				"phaser-editor/first-steps/add-image-to-scene"
			]
		},
		{
			"The Workbench": [
				"phaser-editor/workbench/intro",
				"phaser-editor/workbench/views",
				"phaser-editor/workbench/editors",
				"phaser-editor/workbench/files-view",
				"phaser-editor/workbench/inspector-view",
				"phaser-editor/workbench/outline-view",
				"phaser-editor/workbench/blocks-view",
				"phaser-editor/workbench/main-toolbar",
				"phaser-editor/workbench/main-menu",
				"phaser-editor/workbench/layouts",
				"phaser-editor/workbench/playing-project",
				"phaser-editor/workbench/projects",
				"phaser-editor/workbench/new-file-dialog",
				"phaser-editor/workbench/upload-dialog",
				"phaser-editor/workbench/color-themes",
				"phaser-editor/workbench/command-palette",
				"phaser-editor/workbench/settings"
			]
		},
		{
			"Asset Pack": [
				"phaser-editor/asset-pack-editor/intro",
				"phaser-editor/asset-pack-editor/create-asset-pack-file",
				"phaser-editor/asset-pack-editor/asset-pack-file",
				"phaser-editor/asset-pack-editor/editor-content-layout",
				"phaser-editor/asset-pack-editor/add-file",
				"phaser-editor/asset-pack-editor/organizing-the-assets",
				"phaser-editor/asset-pack-editor/outline-view",
				"phaser-editor/asset-pack-editor/inspector-view"
			]
		},

		//
		// Scene Editor — needs mixed shorthand + explicit categories
		//

		{
			type: "category",
			label: "Scene Editor",
			items: [
				"phaser-editor/scene-editor/intro",
				"phaser-editor/scene-editor/create-new-scene-file",
				"phaser-editor/scene-editor/add-object",
				"phaser-editor/scene-editor/inspector-view",

				//
				// Game Objects (requires full syntax because it uses link:)
				//
				{
					type: "category",
					label: "Game Objects",
					link: { type: "doc", id: "phaser-editor/scene-editor/game-objects" },
					items: [
						"phaser-editor/scene-editor/game-objects/common-object-properties",
						"phaser-editor/scene-editor/game-objects/image-object",
						"phaser-editor/scene-editor/game-objects/sprite-object",
						"phaser-editor/scene-editor/game-objects/tile-sprite-object",
						"phaser-editor/scene-editor/game-objects/nine-slice-object",
						"phaser-editor/scene-editor/game-objects/text-object",
						"phaser-editor/scene-editor/game-objects/bitmap-text-object",
						"phaser-editor/scene-editor/game-objects/tilemap-object",
						"phaser-editor/scene-editor/game-objects/tilemap-layer-object",
						"phaser-editor/scene-editor/game-objects/editable-tilemap-object",
						"phaser-editor/scene-editor/game-objects/editable-tilemap-layer-object",
						"phaser-editor/scene-editor/game-objects/shape-object",
						"phaser-editor/scene-editor/game-objects/shape-rectangle-object",
						"phaser-editor/scene-editor/game-objects/shape-ellipse-object",
						"phaser-editor/scene-editor/game-objects/shape-triangle-object",
						"phaser-editor/scene-editor/game-objects/shape-polygon-object",
						"phaser-editor/scene-editor/game-objects/particle-emitter-object",
						"phaser-editor/scene-editor/game-objects/particle-emitter-object-properties",
						"phaser-editor/scene-editor/game-objects/container-object",
						"phaser-editor/scene-editor/game-objects/layer-object",
						"phaser-editor/scene-editor/game-objects/video-object",
						"phaser-editor/scene-editor/game-objects/spine-game-object",
						"phaser-editor/scene-editor/game-objects/replace-object-type"
					]
				},

				"phaser-editor/scene-editor/scene-properties",

				//
				// Arcade Physics — also has link
				//
				{
					type: "category",
					label: "Arcade Physics",
					link: { type: "doc", id: "phaser-editor/scene-editor/arcade-physics" },
					items: [
						"phaser-editor/scene-editor/arcade-physics/arcade-physics-add-object",
						"phaser-editor/scene-editor/arcade-physics/arcade-physics-add-body",
						"phaser-editor/scene-editor/arcade-physics/arcade-physics-properties",
						"phaser-editor/scene-editor/arcade-physics/arcade-physics-collider"
					]
				},

				//
				// Box2D Physics — has link
				//
				{
					type: "category",
					label: "Box2D Physics",
					link: { type: "doc", id: "phaser-editor/scene-editor/box2d-physics" },
					items: [
						"phaser-editor/scene-editor/box2d-physics/box2d-physics-prepare-scene",
						"phaser-editor/scene-editor/box2d-physics/box2d-physics-add-body",
						"phaser-editor/scene-editor/box2d-physics/box2d-physics-shapes"
					]
				},

				"phaser-editor/scene-editor/sprite-animations",

				//
				// Spine Animations — has link
				//
				{
					type: "category",
					label: "Spine Animations",
					link: { type: "doc", id: "phaser-editor/scene-editor/spine-animations" },
					items: [
						"phaser-editor/scene-editor/spine-animations/spine-animations-install",
						"phaser-editor/scene-editor/spine-animations/spine-animations-loading",
						"phaser-editor/scene-editor/spine-animations/spine-animations-assets-preview",
						"phaser-editor/scene-editor/spine-animations/spine-animations-game-object",
						"phaser-editor/scene-editor/spine-animations/spine-animations-game-object-properties",
						"phaser-editor/scene-editor/spine-animations/spine-animations-game-object-user-properties"
					]
				},

				"phaser-editor/scene-editor/filters",
				"phaser-editor/scene-editor/working-with-spritesheets",
				"phaser-editor/scene-editor/working-with-parent-objects",
				"phaser-editor/scene-editor/object-list",
				"phaser-editor/scene-editor/input",

				//
				// Prefabs — requires link
				//
				{
					type: "category",
					label: "Prefabs",
					link: { type: "doc", id: "phaser-editor/scene-editor/prefabs" },
					items: [
						"phaser-editor/scene-editor/prefabs/prefab-new-file",
						"phaser-editor/scene-editor/prefabs/prefab-object",
						"phaser-editor/scene-editor/prefabs/prefab-user-properties",
						"phaser-editor/scene-editor/prefabs/prefab-create-instance",
						"phaser-editor/scene-editor/prefabs/prefab-display-properties",
						"phaser-editor/scene-editor/prefabs/prefab-code",
						"phaser-editor/scene-editor/prefabs/prefab-set-properties",
						"phaser-editor/scene-editor/prefabs/prefab-variant",
						"phaser-editor/scene-editor/prefabs/prefab-nested",
						"phaser-editor/scene-editor/prefabs/prefab-instance-children",
						"phaser-editor/scene-editor/prefabs/prefab-tags",
						"phaser-editor/scene-editor/prefabs/prefab-unbox",
						"phaser-editor/scene-editor/prefabs/prefab-black-box"
					]
				},

				//
				// Script Node — requires link
				//
				{
					type: "category",
					label: "Script Node",
					link: { type: "doc", id: "phaser-editor/scene-editor/script-node" },
					items: [
						"phaser-editor/scene-editor/script-node/script-node-vs-user-component",
						"phaser-editor/scene-editor/script-node/script-node-libraries",
						"phaser-editor/scene-editor/script-node/script-node-create",
						"phaser-editor/scene-editor/script-node/script-node-class",
						"phaser-editor/scene-editor/script-node/script-node-basic-scripts-project",
						"phaser-editor/scene-editor/script-node/script-node-prefab",
						"phaser-editor/scene-editor/script-node/script-node-properties",
						"phaser-editor/scene-editor/script-node/script-node-constraints"
					]
				},

				//
				// User Components — requires link
				//
				{
					type: "category",
					label: "User Components",
					link: { type: "doc", id: "phaser-editor/scene-editor/user-components" },
					items: [
						"phaser-editor/scene-editor/user-components/user-components-create-file",
						"phaser-editor/scene-editor/user-components/user-components-editor",
						"phaser-editor/scene-editor/user-components/user-components-compiler",
						"phaser-editor/scene-editor/user-components/user-components-start-update-methods",
						"phaser-editor/scene-editor/user-components/user-components-super-class",
						"phaser-editor/scene-editor/user-components/user-components-awake-event",
						"phaser-editor/scene-editor/user-components/user-components-instancing",
						"phaser-editor/scene-editor/user-components/user-components-in-prefab-object",
						"phaser-editor/scene-editor/user-components/user-components-constraints"
					]
				},

				"phaser-editor/scene-editor/manipulation-tools",

				//
				// Layout Tools — requires link
				//
				{
					type: "category",
					label: "Layout Tools",
					link: { type: "doc", id: "phaser-editor/scene-editor/layout-tools" },
					items: [
						"phaser-editor/scene-editor/layout-tools/layout-tools-align",
						"phaser-editor/scene-editor/layout-tools/layout-tools-align-to-border",
						"phaser-editor/scene-editor/layout-tools/layout-tools-origin",
						"phaser-editor/scene-editor/layout-tools/layout-tools-grid",
						"phaser-editor/scene-editor/layout-tools/layout-tools-sorting"
					]
				},

				"phaser-editor/scene-editor/scene-compiler",
				"phaser-editor/scene-editor/misc",
				"phaser-editor/scene-editor/troubleshooting"
			]
		},

		{
			"Animations Editor": [
				"phaser-editor/animations-editor/intro",
				"phaser-editor/animations-editor/new-file-wizard",
				"phaser-editor/animations-editor/add-animation",
				"phaser-editor/animations-editor/auto-build-animations",
				"phaser-editor/animations-editor/edit-animations-properties",
				"phaser-editor/animations-editor/adding-deleting-frames",
				"phaser-editor/animations-editor/compiler"
			]
		},
		{
			"Code Editor": ["phaser-editor/code-editor/intro"]
		},
		{
			"AI": ["phaser-editor/ai/mcp-server"]
		},
		{
			"Miscellaneous": [
				"phaser-editor/misc/project-config",
				"phaser-editor/misc/server-options",
				"phaser-editor/misc/resources-caching",
				"phaser-editor/misc/resources-filtering",
				"phaser-editor/misc/proxy",
				"phaser-editor/misc/local-preferences",
				"phaser-editor/misc/content-viewers",
				"phaser-editor/misc/log-view",
				"phaser-editor/misc/update",
				"phaser-editor/misc/plugins",
				"phaser-editor/misc/troubleshooting"
			]
		},
		{
			type: "link",
			label: "Phaser Discord",
			href: "https://discord.gg/phaser"
		}
	],
};

export default sidebars;
