// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  PhaserEditorSidebar: [
    {
      type: "category",
      label: "Introduction",
      items: [
        { type: "doc", id: "phaser-editor/intro/welcome" },
        { type: "doc", id: "phaser-editor/intro/distributions" },
        { type: "doc", id: "phaser-editor/intro/collaboration" },
        { type: "doc", id: "phaser-editor/intro/changelog" },
      ],
    },
    {
      type: "category",
      label: "First Steps",
      items: [
        { type: "doc", id: "phaser-editor/first-steps/download-and-install" },
        { type: "doc", id: "phaser-editor/first-steps/create-first-project" },
        { type: "doc", id: "phaser-editor/first-steps/add-image-to-scene" },
      ],
    },
    {
      type: "category",
      label: "The Workbench",
      items: [
        { type: "doc", id: "phaser-editor/workbench/intro" },
        { type: "doc", id: "phaser-editor/workbench/views" },
        { type: "doc", id: "phaser-editor/workbench/editors" },
        { type: "doc", id: "phaser-editor/workbench/files-view" },
        { type: "doc", id: "phaser-editor/workbench/inspector-view" },
        { type: "doc", id: "phaser-editor/workbench/outline-view" },
        { type: "doc", id: "phaser-editor/workbench/blocks-view" },
        { type: "doc", id: "phaser-editor/workbench/main-toolbar" },
        { type: "doc", id: "phaser-editor/workbench/main-menu" },
        { type: "doc", id: "phaser-editor/workbench/layouts" },
        { type: "doc", id: "phaser-editor/workbench/playing-project" },
        { type: "doc", id: "phaser-editor/workbench/projects" },
        { type: "doc", id: "phaser-editor/workbench/new-file-dialog" },
        { type: "doc", id: "phaser-editor/workbench/upload-dialog" },
        { type: "doc", id: "phaser-editor/workbench/color-themes" },
        { type: "doc", id: "phaser-editor/workbench/command-palette" },
        { type: "doc", id: "phaser-editor/workbench/settings" },
      ],
    },
    {
      type: "category",
      label: "Asset Pack",
      items: [
        { type: "doc", id: "phaser-editor/asset-pack-editor/intro" },
        { type: "doc", id: "phaser-editor/asset-pack-editor/create-asset-pack-file" },
        { type: "doc", id: "phaser-editor/asset-pack-editor/asset-pack-file" },
        { type: "doc", id: "phaser-editor/asset-pack-editor/editor-content-layout" },
        { type: "doc", id: "phaser-editor/asset-pack-editor/add-file" },
        { type: "doc", id: "phaser-editor/asset-pack-editor/organizing-the-assets" },
        { type: "doc", id: "phaser-editor/asset-pack-editor/outline-view" },
        { type: "doc", id: "phaser-editor/asset-pack-editor/inspector-view" },
      ],
    },
    {
      type: "category",
      label: "Scene Editor",
      items: [
        { type: "doc", id: "phaser-editor/scene-editor/intro" },
        { type: "doc", id: "phaser-editor/scene-editor/create-new-scene-file" },
        { type: "doc", id: "phaser-editor/scene-editor/add-object" },
        { type: "doc", id: "phaser-editor/scene-editor/inspector-view" },
        {
          type: "category",
          label: "Game Objects",
          link: { type: "doc", id: "phaser-editor/scene-editor/game-objects" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/common-object-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/image-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/sprite-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/tile-sprite-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/nine-slice-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/text-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/bitmap-text-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/tilemap-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/tilemap-layer-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/editable-tilemap-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/editable-tilemap-layer-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/shape-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/shape-rectangle-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/shape-ellipse-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/shape-triangle-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/shape-polygon-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/particle-emitter-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/particle-emitter-object-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/container-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/layer-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/video-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/spine-game-object" },
            { type: "doc", id: "phaser-editor/scene-editor/game-objects/replace-object-type" },
          ],
        },
        { type: "doc", id: "phaser-editor/scene-editor/scene-properties" },
        {
          type: "category",
          label: "Arcade Physics",
          link: { type: "doc", id: "phaser-editor/scene-editor/arcade-physics" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/arcade-physics/arcade-physics-add-object" },
            { type: "doc", id: "phaser-editor/scene-editor/arcade-physics/arcade-physics-add-body" },
            { type: "doc", id: "phaser-editor/scene-editor/arcade-physics/arcade-physics-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/arcade-physics/arcade-physics-collider" },
          ],
        },
        {
          type: "category",
          label: "Box2D Physics",
          link: { type: "doc", id: "phaser-editor/scene-editor/box2d-physics" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/box2d-physics/box2d-physics-prepare-scene" },
            { type: "doc", id: "phaser-editor/scene-editor/box2d-physics/box2d-physics-add-body" },
            { type: "doc", id: "phaser-editor/scene-editor/box2d-physics/box2d-physics-shapes" },
          ],
        },
        { type: "doc", id: "phaser-editor/scene-editor/sprite-animations" },
        {
          type: "category",
          label: "Spine Animations",
          link: { type: "doc", id: "phaser-editor/scene-editor/spine-animations" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/spine-animations/spine-animations-install" },
            { type: "doc", id: "phaser-editor/scene-editor/spine-animations/spine-animations-loading" },
            { type: "doc", id: "phaser-editor/scene-editor/spine-animations/spine-animations-assets-preview" },
            { type: "doc", id: "phaser-editor/scene-editor/spine-animations/spine-animations-game-object" },
            { type: "doc", id: "phaser-editor/scene-editor/spine-animations/spine-animations-game-object-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/spine-animations/spine-animations-game-object-user-properties" },
          ],
        },
        { type: "doc", id: "phaser-editor/scene-editor/filters" },
        { type: "doc", id: "phaser-editor/scene-editor/working-with-spritesheets" },
        { type: "doc", id: "phaser-editor/scene-editor/working-with-parent-objects" },
        { type: "doc", id: "phaser-editor/scene-editor/object-list" },
        { type: "doc", id: "phaser-editor/scene-editor/input" },
        {
          type: "category",
          label: "Prefabs",
          link: { type: "doc", id: "phaser-editor/scene-editor/prefabs" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-new-file" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-object" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-user-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-create-instance" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-display-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-code" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-set-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-variant" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-nested" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-instance-children" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-tags" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-unbox" },
            { type: "doc", id: "phaser-editor/scene-editor/prefabs/prefab-black-box" },
          ],
        },
        {
          type: "category",
          label: "Script Node",
          link: { type: "doc", id: "phaser-editor/scene-editor/script-node" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-vs-user-component" },
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-libraries" },
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-create" },
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-class" },
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-basic-scripts-project" },
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-prefab" },
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-properties" },
            { type: "doc", id: "phaser-editor/scene-editor/script-node/script-node-constraints" },
          ],
        },
        {
          type: "category",
          label: "User Components",
          link: { type: "doc", id: "phaser-editor/scene-editor/user-components" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-create-file" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-editor" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-compiler" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-start-update-methods" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-super-class" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-awake-event" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-instancing" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-in-prefab-object" },
            { type: "doc", id: "phaser-editor/scene-editor/user-components/user-components-constraints" },
          ],
        },
        { type: "doc", id: "phaser-editor/scene-editor/manipulation-tools" },
        {
          type: "category",
          label: "Layout Tools",
          link: { type: "doc", id: "phaser-editor/scene-editor/layout-tools" },
          items: [
            { type: "doc", id: "phaser-editor/scene-editor/layout-tools/layout-tools-align" },
            { type: "doc", id: "phaser-editor/scene-editor/layout-tools/layout-tools-align-to-border" },
            { type: "doc", id: "phaser-editor/scene-editor/layout-tools/layout-tools-origin" },
            { type: "doc", id: "phaser-editor/scene-editor/layout-tools/layout-tools-grid" },
            { type: "doc", id: "phaser-editor/scene-editor/layout-tools/layout-tools-sorting" },
          ],
        },
        { type: "doc", id: "phaser-editor/scene-editor/scene-compiler" },
        { type: "doc", id: "phaser-editor/scene-editor/misc" },
        { type: "doc", id: "phaser-editor/scene-editor/troubleshooting" },
      ],
    },
    {
      type: "category",
      label: "Animations Editor",
      items: [
        { type: "doc", id: "phaser-editor/animations-editor/intro" },
        { type: "doc", id: "phaser-editor/animations-editor/new-file-wizard" },
        { type: "doc", id: "phaser-editor/animations-editor/add-animation" },
        { type: "doc", id: "phaser-editor/animations-editor/auto-build-animations" },
        { type: "doc", id: "phaser-editor/animations-editor/edit-animations-properties" },
        { type: "doc", id: "phaser-editor/animations-editor/adding-deleting-frames" },
        { type: "doc", id: "phaser-editor/animations-editor/compiler" },
      ],
    },
    {
      type: "category",
      label: "Code Editor",
      items: [{ type: "doc", id: "phaser-editor/code-editor/intro" }],
    },
    {
      type: "category",
      label: "AI",
      items: [{ type: "doc", id: "phaser-editor/ai/mcp-server" }],
    },
    {
      type: "category",
      label: "Miscellaneous",
      items: [
        { type: "doc", id: "phaser-editor/misc/project-config" },
        { type: "doc", id: "phaser-editor/misc/server-options" },
        { type: "doc", id: "phaser-editor/misc/resources-caching" },
        { type: "doc", id: "phaser-editor/misc/resources-filtering" },
        { type: "doc", id: "phaser-editor/misc/proxy" },
        { type: "doc", id: "phaser-editor/misc/local-preferences" },
        { type: "doc", id: "phaser-editor/misc/content-viewers" },
        { type: "doc", id: "phaser-editor/misc/log-view" },
        { type: "doc", id: "phaser-editor/misc/update" },
        { type: "doc", id: "phaser-editor/misc/plugins" },
        { type: "doc", id: "phaser-editor/misc/troubleshooting" },
      ],
    },
    {
      type: "link",
      label: "Phaser Discord",
      href: "https://discord.gg/phaser",
    }
  ],
};

export default sidebars;
